[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = { version = "0.22.0", features = ["lexer", "unicode"] }
